- src/stories/_argument.py
- tests/test_argument.py
Just a simple QoL improvement to avoid too much decorators on stories. 
Tested and backward compatible.
> @argument decorator now accepts multiple arguments

- docs/why.rst
Found some typos while reading the docs.
> Fix some typos.

- docs/composition.md
- tests/helpers/mddoctest.py
- tox.ini
I need to think about how to fix the rest.
> Fix some doctests

- azure-pipelines.yml
- release.config.js
- tox.ini
Apply pre-commit hooks (i.e. prettier) to the generated changelog before committing it to the codebase.
> Prevent generated changelog from style guide violation.

- src/_stories/compat.py
- src/_stories/contract.py
- src/_stories/contract.pyi
- tox.ini
> Migrate to Pydantic v1.x

- tox.ini
This plugin should display test results in the UI.
Let's see how it works...
> Use a pytest plugin to integrate with azurepipelines

- src/_stories/contract.py
- tests/test_configuration.py
- tox.ini
I included a few more plugins.
We also now run flake8 in parallel.
> Flake8 improvements

- azure-pipelines.yml
- src/_stories/compat.py
- src/_stories/contract.py
- tests/helpers/examples/__init__.py
- tests/helpers/examples/contract/marshmallow2/__init__.py
- tests/helpers/examples/contract/marshmallow2/coroutines.py
- tests/helpers/examples/contract/marshmallow2/functions.py
- tests/helpers/examples/contract/marshmallow3/__init__.py
- tests/helpers/examples/contract/marshmallow3/coroutines.py
- tests/helpers/examples/contract/marshmallow3/functions.py
- tests/helpers/helpers.py
- tests/test_configuration.py
- tox.ini
> Support Marshmallow 3.

- .readthedocs.txt
- .readthedocs.yml
- pyproject.toml
- tests/test_configuration.py
- tox.ini
> Move mkdocs out of pyproject.toml.

- azure-pipelines.yml
- dangerfile.ts
- package.json
> Adapt danger tool.

- tests/test_configuration.py
> Ensure multiline tox settings are written on the new line.

- .flake8
> Ignore E741 pycodestyle error.

- azure-pipelines.yml
- dangerfile.ts
> Improve dangerfile.

- mkdocs.yml
> Use tabbed layout in the documentation site.

- README.md
- azure-pipelines.yml
- pyproject.toml
> Deploy documentation to the GitHub pages.

- .pre-commit-config.yaml
- .prettierignore
- release.config.js
- tests/test_configuration.py
- tox.ini
> Migrate from pre-commit to tox.

- docs/index.md
> Asking questions on the task tracker.

- .gitignore
- tests/test_arguments.py
- tests/test_configuration.py
- tests/test_contract.py
- tests/test_execute.py
- tests/test_failure_reasons.py
- tests/test_story.py
- tox.ini
> Isolate npm installation in different directories.

- src/_stories/collect.py
- tests/test_story.py
> Prevent story to call itself recursively.

- dangerfile.ts
- docs/changelog.md
> Improve dangerfile rules.

- azure-pipelines.yml
- docs/changelog.md
- docs/composition.md
- docs/contrib/debug_toolbars.md
- docs/contrib/pytest.md
- docs/contrib/sentry.md
- docs/debugging.md
- docs/definition.md
- docs/execution.md
- docs/failure_protocol.md
- docs/faq.md
- docs/index.md
- docs/usage.md
- docs/why.md
- tox.ini
> Enable prose wrap prettier option.

- src/_stories/collect.py
- tests/test_story.py
> Deny to use same story step twice.

- docs/changelog.md
- docs/index.md
> Introduce enterprise support.

- docs/composition.md
- docs/definition.md
- docs/execution.md
- docs/failure_protocol.md
- docs/index.md
- docs/installation.md
- docs/usage.md
- mkdocs.yml
> Correct code blocks.

- dangerfile.ts
> Validate repository label colors.

- docs/contrib_debug_toolbars.md
- docs/contrib_pytest.md
- docs/contrib_sentry.md
- docs/index.md
- mkdocs.yml
> Remove tabbed content from GitHub README file.
